services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb:/chroma/chroma
    restart: always
    environment:
      - IS_PERSISTENT=TRUE
